version: '3.3'
services:
    dandd:
        container_name: "dandd-quartz"
        restart: always
        build: .
        ports:
            - '1313:1313'
        environment:
            - HUGO_BIND=0.0.0.0
            - HUGO_BASEURL=https://dandd.declanmorris.com
            - HUGO_PORT=1313
            - HUGO_APPENDPORT=false
            - HUGO_LIVERELOADPORT=-1
