name: Docker

on:
  push:
    branches: [ "hugo" ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.DANDD_PAT }}
    
    - name: SCP Files
      uses: appleboy/scp-action@v0.1.3
      with:
        host: declanmorris.com
        username: dtm
        KEY: ${{ secrets.VPS_SSHKEY }}
        port: 22
        source: "*"
        target: /opt/docker/dnd

    - name: Deploy latest changes on VPS
      uses: appleboy/ssh-action@master
      with:
          host: declanmorris.com
          USERNAME: dtm
          PORT: 22
          KEY: ${{ secrets.VPS_SSHKEY }}
          script: cd /opt/docker/dnd && docker-compose up --build -d

#    - name: Pull latest changes on VPS
 #     uses: appleboy/ssh-action@master
  #    with:
   #       host: declanmorris.com
    #      USERNAME: dtm
     #     PORT: 22
      #    KEY: ${{ secrets.VPS_SSHKEY }}
       #   script: cd /opt/docker/dnd && git pull
